// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtQr7Jo4oDrCH5DLWK7npcrnwEZSuVybI',
    appId: '1:484406782701:web:74f3e9cfdf2abee2b4bae4',
    messagingSenderId: '484406782701',
    projectId: 'login-playground-app',
    authDomain: 'login-playground-app.firebaseapp.com',
    storageBucket: 'login-playground-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeDXbpATam7QNL0XGIR4GP2RYO2_diaU0',
    appId: '1:484406782701:android:0fcc80af765e130eb4bae4',
    messagingSenderId: '484406782701',
    projectId: 'login-playground-app',
    storageBucket: 'login-playground-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLp9Dah_eY8B_sXYV4xg8qAbh_8Nllzkc',
    appId: '1:484406782701:ios:8d91ec3433ad46bfb4bae4',
    messagingSenderId: '484406782701',
    projectId: 'login-playground-app',
    storageBucket: 'login-playground-app.appspot.com',
    androidClientId:
        '484406782701-mngdn9n6u7i62j8j18cdkhbub5c7urbl.apps.googleusercontent.com',
    iosClientId:
        '484406782701-kadtsjqeo6mr91jgpkub3812bv1d2p8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin',
  );
}
